version: '3.8'

services:
  backup:
    container_name: backup
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - CROUStillantNetwork

networks:
  CROUStillantNetwork:
    external: true
